name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: echo "Wassup Y'all"

  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Wait
      run: echo "Nothing to do yet..."
